name: Testes

on: [push, pull_request]

jobs:
  testes:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
          - windows-2019
        python-version: [3.10]

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2.4.2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip

    - name: Executar testes
      run: python -m unittest discover -s . -p '*_test.py'
