name: Testes

on: [push, pull_request]

jobs:
  testes:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.x]  # Substitua 'x' pela versão do Python que você está usando

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Substitua pelo caminho do seu arquivo requirements.txt, se aplicável

    - name: Executar testes
      run: python -m unittest discover -s . -p '*_test.py'  # Substitua pelo padrão de nomenclatura dos seus arquivos de teste
